env:
  browser: true
  es6: true
  node: false
  amd: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  Set: readonly
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - es5
  - react
rules:
  no-unused-vars: ["error", {vars: "all", args: "none"}]
  no-prototype-builtins: [ "off" ]
  no-fallthrough: ["error", { "commentPattern": "no-break" }]
  react/jsx-uses-vars: 1
  import/no-webpack-loader-syntax: [ "off" ]
